Repository acm-ucr/r-mate, pull requests merged in 2023-06, with the labels that each got.

#118 Dining Hour Display
  src/components/FoodHours.jsx
  src/components/data/DiningData.jsx
  src/components/data/MarketsData.jsx
Labels: ready to review, food

#119 Food card
  src/components/FoodCard.jsx
  src/components/data/MarketsData.jsx
Labels: ready to review

#116 Added styling to radio question/button
  src/components/RadioButton.jsx
  src/components/RadioQuestion.jsx
Labels: survey screen

#115 Add parking lot filter
  src/components/ParkingLotFilter.jsx
Labels: parking

#120 Food Detail Page
  src/components/FoodDetailPage.jsx
Labels: ready to review
