Repository acm-ucr/r-mate, pull requests merged in 2023-05, with the labels that each got.

#62 Convert to Native
  src/components/Bug.jsx
Labels: profile screen, easy

#63 Converted to Nativewind Account Display
  src/components/Account.jsx
Labels: ready to review

#65 Zacharygreen2003/navbar
  assets/UCRNavbarLogo.svg
  src/navigators/BottomNavigator.jsx
Labels: navigation, mid

#66 Bottom nav bar wider
  src/components/BottomBar.jsx
Labels: navigation, easy

#77 grab bug information
  src/components/Bug.jsx
Labels: ready to review

#80 SRC Events Card
  src/components/SRCEventsCard.jsx
Labels: ready to review

#79 Add SRCCountCard
  package-lock.json
  package.json
  src/components/SRCCountCard.jsx
Labels: SRC

#85 Remove unused TouchableOpacity from component
  src/components/TopBar.jsx
Labels: ready to review

#84 Alamode89/src hour button
  src/components/SRC.jsx
  src/components/SRCHourButton.jsx
  tailwind.config.js
Labels: ready to review

#87 Falak/src program card
  src/components/SRCProgramCard.jsx
Labels: SRC

#89 Added profilesvg to topbar
  src/navigators/Navigator.jsx
Labels: ready to review

#109 Bottom bar fills in icon with respect to current screen
  src/components/BottomBar.jsx
Labels: navigation

#113 Created back button
  src/components/BackButton.jsx
Labels: ready to review

#108 SRC Dropdown
  app.json
  src/components/SRCDropdown.jsx
  src/components/SRCPrograms.jsx
Labels: ready to review, do not merge, SRC
