Repository acm-ucr/r-mate, pull requests merged in 2023-04, with the labels that each got.

#20 Profile Page
  src/components/Profile.jsx
Labels: profile screen, ready to review

#21 Loading Page
  src/screens/loading.js
Labels: ready to review

#22 Bug Screen
  src/components/Bug.jsx
Labels: ready to review

#23 create title component
  src/components/Title.jsx
Labels: ready to review

#24 create resources card
  src/components/ResourcesCard.jsx
Labels: ready to review

#26 Added Feedback page
  src/components/Feedback.jsx
Labels: profile screen, ready to review

#25 Add icons to BottomBar component
  src/components/BottomBar.jsx
Labels: navigation

#32 Changed from style sheet to tailwind utility class
  src/components/Feedback.jsx
Labels: profile screen, easy

#31 Digital R'Card template with rounded border corners
  src/components/RCard.jsx
Labels: ready to review

#36 Store user feedback and output to console
  src/components/Feedback.jsx
Labels: profile screen

#44 Zgree004/Login Page
  src/screens/login.js
Labels: login screen

#48 Add Maps
  package-lock.json
  package.json
  src/screens/map.js
Labels: ready to review

#50 Account
  src/components/Account.jsx
Labels: profile screen, mid

#49 RMate Context
  App.js
  src/components/Profile.jsx
  src/components/RMateContext.jsx
Labels: ready to review

#52 EventPage updated with basic description, background photo and functi…
  src/components/EventPage.jsx
Labels: ready to review

#59 Native wind in Title.jsx
  src/components/Feedback.jsx
  src/components/Title.jsx
Labels: home screen, clean up

#57 welcome
  src/components/Welcome.jsx
  src/screens/branch.env
  src/screens/home.js
Labels: ready to review

#60 Add CalendarEvents component
  package-lock.json
  package.json
  src/components/Calendar.jsx
  src/components/CalendarEvents.jsx
  src/screens/events.js
Labels: events screen
